name: LaTeX Action
description: LaTeX documents processing action
author: Autonomy Organisation
branding:
  icon: code
  color: blue
inputs:
  main_file:
    description: The main LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for the LaTeX compiler to be invoked
    default: "."
  compiler:
    description: LaTeX engine to be used
    default: latexmk
  compiler_options:
    description: Extra arguments to be passed to the LaTeX compiler
    default: "-lualatex -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.main_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.compiler_options }}